# Generated by Django 2.1.3 on 2018-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181106_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
