# Generated by Django 2.1.3 on 2018-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181223_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag_list',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
