# Generated by Django 2.1.3 on 2018-12-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
